version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook
    volumes:
      - ./work:/home/jovyan/work 
    ports:
      - "8888:8888"

  mongodb:
    image: mongo:3.6.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

networks:
  default:
    name: jupyter_mongo_net
