version: '3'

services:
  jupyter:
    image: jupyter/base-notebook
    volumes:
      - ..:/home/jovyan/work
    ports:
      - 8888:8888
    links:
      - mongodb
    networks:
      jupyter_mongo_net:

  mongodb:
    image: mongo:3.6.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: testuser
      MONGODB_PASSWORD: testpassword
    volumes:
      - ./data/db:/data/db
    networks:
      jupyter_mongo_net:

networks:
  jupyter_mongo_net:
