version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:0.4.20
    ports:
      - "8000:8000"  
    volumes:
      - ./chromadb-data:/var/lib/chromadb  
